---

- name: Deploy ingest & sla plugins to your ES cluster
  hosts: esdata
  become: yes
  gather_facts: True
  tasks:
    - name: Deploy ingest plugin
      include_role:
        name: elasticsearch-deploy-plugin-common 
      vars:
        es_repo: elasticsearch-sla
        plugins_name: siconia-kpi-ingests
        plugins_version: 1.0.26

