---

- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload


- name: restart elasticsearch
  become: yes
  service: name={{ es_systemd_script | basename}} state=restarted enabled=yes
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted
